apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-project-database-config
  namespace: kiii
data:
  POSTGRES_DB: book-library
  POSTGRES_USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: kiii-project-database-secret
  namespace: kiii
type: Opaque
data:
  password: cG9zdGdyZXM=

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiii-project-database-pvc3
  namespace: kiii
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kiii-project-database-statefulset
  namespace: kiii
spec:
  serviceName: kiii-project-database-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        namespace: kiii
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: kiii-project-database-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kiii-project-database-secret
                  key: password
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - name: kiii-project-database-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: kiii-project-database-data
          persistentVolumeClaim:
            claimName: kiii-project-database-pvc3
---
apiVersion: v1
kind: Service
metadata:
  name: kiii-project-database-service
  namespace: kiii
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      